// src/utilities/colors.js
export const colors = [
	{ label: 'Primary', value: 'primary' },
	{ label: 'Dark', value: 'dark' },
	{ label: 'Light', value: 'light' },
	{ label: 'Primary', value: 'primary' },
	{ label: 'Dark', value: 'dark' },
	{ label: 'Light', value: 'light' },
	{ label: 'Yellow', value: 'yellow' },
	{ label: 'Orange', value: 'orange' },
	{ label: 'Red', value: 'red' },
	{ label: 'Pink', value: 'pink' },
	{ label: 'Fuchsia', value: 'fuchsia' },
	{ label: 'Violet', value: 'violet' },
	{ label: 'Purple', value: 'purple' },
	{ label: 'Blue', value: 'blue' },
	{ label: 'Aqua', value: 'aqua' },
	{ label: 'Sky', value: 'sky' },
	{ label: 'Green', value: 'green' },
	{ label: 'Leaf', value: 'leaf' },
	{ label: 'Ash', value: 'ash' },
	{ label: 'Navy', value: 'navy' },
	{ label: 'Grape', value: 'grape' },
	{ label: 'Muted', value: 'muted' },
	{ label: 'White', value: 'white' },
	{ label: 'Gradient 1', value: 'gradient gradient-1' },
	{ label: 'Gradient 2', value: 'gradient gradient-2' },
	{ label: 'Gradient 3', value: 'gradient gradient-3' },
	{ label: 'Gradient 4', value: 'gradient gradient-4' },
	{ label: 'Gradient 5', value: 'gradient gradient-5' },
	{ label: 'Gradient 6', value: 'gradient gradient-6' },
	{ label: 'Gradient 7', value: 'gradient gradient-7' },
	{ label: 'Gradient 8', value: 'gradient gradient-8' },
	{ label: 'Pinterest', value: 'pinterest' },
	{ label: 'Dewalt', value: 'dewalt' },
];
